# nixpacks.toml - Railway build configuration

[phases.setup]
nixPkgs = ["python311", "tesseract", "poppler_utils", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
