# nixpacks.toml - Railway build configuration

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "uvicorn simple_main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
